Uncomment and finish job run-migrations

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -195,23 +195,32 @@ jobs:
               ~/project/.circleci/ansible/configure-server.yml
       - destroy-environment
 
-#  run-migrations:
-#    docker:
-#      # Docker image here that supports NodeJS
-#    steps:
-#      # Checkout code from git
-#      - run:
-#          name: Run migrations
-#          command: |
-#            # Your code here
-#            exit 1
-#      - run:
-#          name: Send migration results to memstash
-#          command: |
-#            # Your code here
-#            exit 1
-#     # Here's where you will add some code to rollback on failure
-#
+  run-migrations:
+    docker:
+      - image: circleci/node:13.8.0
+    steps:
+      - checkout
+      - run:
+          name: Run migrations
+          command: |
+            npm run migrations > ~/project/.circleci/migrations_output.txt
+            exit 1
+      - run:
+          name: Send migration results to memstash
+          command: |
+            if [ $(grep "has been executed successfully" ~/project/.circleci/migrations_output.txt) ] then
+              export MIGRATION_RESULT="1"
+            else
+              export MIGRATION_RESULT="0"
+            fi
+            curl -H "Content-Type: text/plain" \
+              -H "token: b1cbdda4-c2dd-46e4-ae4e-91babf05fb00" \
+              --request PUT \
+              --data "$MIGRATION_RESULT" \
+              https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID}
+            exit 1
+     # Here's where you will add some code to rollback on failure
+
 #  deploy-frontend:
 #    docker:
 #      # Docker image here that supports AWS CLI
@@ -328,8 +337,8 @@ workflows:
               only: [master]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
-#      - run-migrations:
-#          requires: [configure-infrastructure]
+      - run-migrations:
+          requires: [configure-infrastructure]
 #      - deploy-frontend:
 #          requires: [run-migrations]
 #      - deploy-backend:
